Repository shapely/shapely, pull requests merged in 2020-11, with the labels that each got.

#1017 Deprecate the geometry .empty() method
  shapely/geometry/base.py
  shapely/geometry/linestring.py
  shapely/geometry/point.py
  shapely/geometry/polygon.py
  tests/test_emptiness.py
Labels: deprecation

#1019 Refactor affine_transform: use general function apply on coordinates
  shapely/affinity.py
  shapely/speedups/__init__.py
  shapely/speedups/_speedups.pyx
Labels: shapely 2.0

#1025 Deprecate ops.cascaded_union, as it was superseded by ops.unary_union
  docs/conf.py
  docs/manual.rst
  shapely/ops.py
  tests/test_split.py
  tests/test_union.py
Labels: deprecation

#1008 Substring: negative values and direction issues + more robust testing
  docs/manual.rst
  shapely/ops.py
  tests/test_substring.py
Labels: enhancement
