Repository shapely/shapely, pull requests merged in 2025-02, with the labels that each got.

#2214 BUG: Gracefully handle calling orient() on empty polygon
  shapely/geometry/polygon.py
  shapely/tests/legacy/test_orient.py
Labels: bug

#2232 DOC: improve doc regarding validness of polygons
  docs/manual.rst
Labels: documentation

#2237 DEPR: deprecate positional args in some functions
  shapely/_geometry.py
  shapely/constructive.py
  shapely/coordinates.py
  shapely/creation.py
  shapely/decorators.py
  shapely/geometry/base.py
  shapely/geometry/linestring.py
  shapely/linear.py
  shapely/ops.py
  shapely/predicates.py
  shapely/set_operations.py
  shapely/tests/geometry/test_format.py
  shapely/tests/geometry/test_geometry_base.py
  shapely/tests/geometry/test_linestring.py
  shapely/tests/geometry/test_polygon.py
  shapely/tests/legacy/test_operations.py
  shapely/tests/test_constructive.py
  shapely/tests/test_coordinates.py
  shapely/tests/test_creation.py
  shapely/tests/test_creation_indices.py
  shapely/tests/test_geometry.py
  shapely/tests/test_linear.py
  shapely/tests/test_set_operations.py
Labels: deprecation
